# Compiling settings
# You can turn-off compiling of specific modules here by setting them to `false`
nms.compile_v1_8=false
nms.compile_v1_12=false
nms.compile_v1_16=false
nms.compile_v1_17=false
nms.compile_v1_18=false
nms.compile_v1_19=false
nms.compile_v1_20=false
nms.compile_v1_21=true
nms.compile_v26_1=true
nms.compile_v26_2=true
hook.compile_chestshop=true
hook.compile_cmi=false
hook.compile_coreprotect=true
hook.compile_folia=true
hook.compile_economyshopgui=false
hook.compile_essentials=true
hook.compile_quantumshop=false
hook.compile_rosestacker=true
hook.compile_shopguiplus12=true
hook.compile_shopguiplus14=true
hook.compile_superiorskyblock=false
hook.compile_transportpipes=false
hook.compile_vault=true
hook.compile_wildstacker=false
hook.compile_zshop=false
